services:
  - type: web
    name: share-notes-api
    env: node
    region: oregon
    plan: free
    rootDir: share-notes-backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://share-notes-api.onrender.com/api/auth/google/callback
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false

  - type: static
    name: share-notes-frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    rootDir: share-notes-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: CI
        value: false
